name: ldha-drug-discovery
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.1
  - numpy=1.26.4
  - rdkit=2022.09.5
  - scikit-learn=1.4.1
  - mordred=1.2.0
  - xgboost=2.0.3
  - lightgbm=4.3.0
  - catboost=1.2.3
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - joblib=1.3.2
  - optuna=3.5.0
  - shap=0.44.1
  - streamlit=1.32.2
  - tqdm=4.66.2
